# Generated by Django 6.0 on 2025-12-09 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgenteVirtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='AVI Assistant', max_length=100, verbose_name='Nombre del Agente')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('avatar_3d_url', models.URLField(blank=True, null=True, verbose_name='URL del Modelo 3D del Avatar')),
                ('voz_configurada', models.CharField(default='es-ES', max_length=100, verbose_name='Configuración de Voz TTS')),
                ('idioma_objetivo', models.CharField(default='en-US', help_text='Idioma que el agente enseña', max_length=50, verbose_name='Idioma Objetivo')),
                ('personalidad', models.JSONField(blank=True, null=True, verbose_name='Configuración de Personalidad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Agente Virtual',
                'verbose_name_plural': 'Agentes Virtuales',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=100, verbose_name='Nombre del Servicio')),
                ('tipo', models.CharField(choices=[('ASR', 'Reconocimiento de Voz (ASR)'), ('NLP', 'Procesamiento de Lenguaje Natural (NLP)'), ('TTS', 'Síntesis de Voz (TTS)')], max_length=10, verbose_name='Tipo de Servicio')),
                ('configuracion', models.JSONField(blank=True, help_text='Configuración específica del servicio en formato JSON', null=True, verbose_name='Configuración')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Servicio',
                'verbose_name_plural': 'Configuraciones de Servicio',
            },
        ),
        migrations.CreateModel(
            name='Retroalimentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_original', models.TextField(help_text='Lo que dijo el estudiante', verbose_name='Texto Original')),
                ('texto_esperado', models.TextField(blank=True, help_text='Lo que debería haber dicho', null=True, verbose_name='Texto Esperado')),
                ('texto_corregido', models.TextField(blank=True, help_text='Corrección sugerida', null=True, verbose_name='Texto Corregido')),
                ('puntuacion_pronunciacion', models.FloatField(default=0.0, verbose_name='Puntuación de Pronunciación')),
                ('puntuacion_fluidez', models.FloatField(default=0.0, verbose_name='Puntuación de Fluidez')),
                ('puntuacion_entonacion', models.FloatField(default=0.0, verbose_name='Puntuación de Entonación')),
                ('puntuacion_ritmo', models.FloatField(default=0.0, verbose_name='Puntuación de Ritmo')),
                ('errores_gramaticales', models.JSONField(blank=True, default=list, null=True, verbose_name='Errores Gramaticales')),
                ('sugerencias', models.JSONField(blank=True, default=list, null=True, verbose_name='Sugerencias de Mejora')),
                ('fonemas_problematicos', models.JSONField(blank=True, default=list, null=True, verbose_name='Fonemas Problemáticos')),
                ('palabras_problematicas', models.JSONField(blank=True, default=list, null=True, verbose_name='Palabras Problemáticas')),
                ('audio_estudiante', models.FileField(blank=True, null=True, upload_to='audios/estudiantes/', verbose_name='Audio del Estudiante')),
                ('audio_correccion', models.FileField(blank=True, null=True, upload_to='audios/correcciones/', verbose_name='Audio de Corrección')),
                ('respuesta_agente', models.TextField(blank=True, null=True, verbose_name='Respuesta del Agente')),
                ('audio_respuesta', models.FileField(blank=True, null=True, upload_to='audios/respuestas/', verbose_name='Audio de Respuesta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('tiempo_respuesta_ms', models.PositiveIntegerField(default=0, verbose_name='Tiempo de Respuesta (ms)')),
            ],
            options={
                'verbose_name': 'Retroalimentación',
                'verbose_name_plural': 'Retroalimentaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SesionPractica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Título')),
                ('tema_practica', models.CharField(blank=True, help_text='Ej: Saludos, Restaurante, Entrevista de trabajo', max_length=200, null=True, verbose_name='Tema de Práctica')),
                ('nivel_dificultad', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nivel de Dificultad')),
                ('duracion_minutos', models.PositiveIntegerField(default=0, verbose_name='Duración (minutos)')),
                ('palabras_practicadas', models.PositiveIntegerField(default=0, verbose_name='Palabras Practicadas')),
                ('frases_correctas', models.PositiveIntegerField(default=0, verbose_name='Frases Correctas')),
                ('frases_incorrectas', models.PositiveIntegerField(default=0, verbose_name='Frases Incorrectas')),
                ('puntuacion_sesion', models.FloatField(default=0.0, help_text='Puntuación de 0 a 100', verbose_name='Puntuación de la Sesión')),
                ('estado', models.CharField(choices=[('iniciada', 'Iniciada'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('pausada', 'Pausada')], default='iniciada', max_length=20, verbose_name='Estado')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('historial_conversacion', models.JSONField(blank=True, default=list, null=True, verbose_name='Historial de Conversación')),
                ('agente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones', to='chatbot.agentevirtual', verbose_name='Agente Virtual')),
            ],
            options={
                'verbose_name': 'Sesión de Práctica',
                'verbose_name_plural': 'Sesiones de Práctica',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
