# Generated by Django 6.0 on 2025-12-09 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatbot', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionpractica',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='users.estudiante', verbose_name='Estudiante'),
        ),
        migrations.AddField(
            model_name='retroalimentacion',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retroalimentaciones', to='chatbot.sesionpractica', verbose_name='Sesión'),
        ),
    ]
